version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: dbglobe_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5434:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: expense-tracker-app:latest
    container_name: expense-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dbglobe_db
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: db_password
      BACKENDAPI_APP_JWTSECRET: dbglobe
      BACKENDAPI_APP_JWTEXPIRATIONMS: 8640000
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
