spring:
  application:
    name: expense-tracker-app
  datasource:
    url: 'jdbc:postgresql://localhost:5434/dbglobe_db'
    username: db_user
    password: db_password
  flyway:
    baseline-on-migrate: true
    baseline-version: 20240517143450
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
backendapi:
  app:
    jwtSecret: dbglobe
    jwtExpirationMs: '8640000'
logging:
  level:
    org:
      springframework:
        web: WARN
      hibernate: INFO
    com:
      project: INFO
